api = "0.4"

[buildpack]
id = "heroku/java"
version = "0.1.4"
name = "Java"

[[order]]

[[order.group]]
id = "heroku/jvm"
version = "1.0.0"

[[order.group]]
id = "heroku/maven"
version = "0.2.1"

[[order.group]]
id = "heroku/procfile"
version = "0.6.1"
optional = true

[[order]]

[[order.group]]
id = "heroku/gradle"
version = "0.4.0"

[[order.group]]
id = "heroku/procfile"
version = "0.6.1"
optional = true

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/r2f9u0w4/heroku-java-buildpack"
